### ISSUE TITLE
Android Iconize Not Building With Xamarin 4.4

### ISSUE THREAD

**Issue by DevBuzzker** [jsmarcus/Iconize#171]
When upgrading from 4.3.0.908675 to 4.4.0.991477 android project build fails. iOS works fine.
Build exception:

XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void Plugin.Iconize.IconNavigationRenderer::UpdateMenuItemIcon(Android.Content.Context,Android.Views.IMenuItem,Xamarin.Forms.ToolbarItem)' in assembly: 'Plugin.Iconize.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer::UpdateMenuItemIcon(Android.Content.Context,Android.Views.IMenuItem,Xamarin.Forms.ToolbarItem)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()

**Comment by landrzz** [comment]
I am having the same issue!

**Comment by alialdemir** [comment]
+1

**Comment by microwales** [comment]
Same here as well

**Comment by RedasP** [comment]
Is there a know workaround?

**Comment by microwales** [comment]
> Is there a know workaround?

The only work around I know was to downgrade the xamarin forms to 4.3.0.991250

**Comment by arielcattaneo** [comment]
In Xamarin.Forms **4.4.0.991640** work!

**Comment by microwales** [comment]
> In Xamarin.Forms **4.4.0.991640** work!

UPDATE: 
It works for me as well. Thanks
