### ISSUE TITLE
Could not load assembly "Plugin.Iconize.Droid, Version=1.5.0.13"

### ISSUE THREAD

**Issue by ojhariddhish** [jsmarcus/Iconize#37]
I've installed these plugins in my Xamarin Forms solution (in all projects):
Xam.FormsPlugin.Iconize (1.5.0.13-beta)
Xam.Plugin.Iconize (2.0.0.29-beta)
Xam.Plugin.Iconize.FontAwesome (2.0.0.29-beta)

When I try to run the application after setting up the font and its usages in XAML files, I get this error:
**Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Plugin.Iconize.Droid, Version=1.5.0.13, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?**

**_File name: 'Plugin.Iconize.Droid.dll'_**
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)

I'm new to Xamarin Forms and I have no idea why is this issue occurring. Any help will be greatly appreciated.

**Comment by beko1997** [comment]
I guess the issue is located to the NuGet package `Xam.FormsPlugin.Iconize (1.5.0.13-beta)`. It seems to be a previous version of this package which is still available in NuGet. 

Could you please try to remove that specific package? 

Below is my current set-up which seems to work:

NuGet installed (In PCL, Android and iOS):
- Xam.Plugin.Iconize
- Xam.Plugin.Iconize.FontAwesome

**View.xaml**
````xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage x:Name="Page"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:iconize="clr-namespace:Plugin.Iconize;assembly=Plugin.Iconize">
        <iconize:IconLabel Text="fa-clock-o"></iconize:IconLabel>
</ContentPage>
````

**App.xaml.cs (PCL)**
````cs
        public App()
        {
            InitializeComponent();
            Iconize
                          .With(new Plugin.Iconize.Fonts.FontAwesomeModule())
                          .With(new Plugin.Iconize.Fonts.MaterialModule());

            MainPage = new NavigationPage(new View());
        }
````

**Info.plist (iOS)**
````xml
  <key>UIAppFonts</key>
  <array>
    <string>iconize-fontawesome.ttf</string>
    <string>iconize-material.ttf</string>
  </array>
````
Insert this inside the `<dict>` element. You can specify multiple .ttf files, please add the files to the iOS project `/Resources` folder.

**Comment by ojhariddhish** [comment]
@beko1997 thanks. Will try it out your way.

**Comment by DCubix** [comment]
Plugin.Iconize.Iconize has no Init method

**Comment by nivibhat** [comment]
I am getting FormsPlugin could not be found error.
